### ISSUE TITLE
Help community-packages migrate to new scope name

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/language-c#56]
Once #55 is released, send PRs to these packages. For now, they should probably handle both the old scopes (`source.c++`, `source.objc++`) and the new scopes (`source.cpp`, `source.objcpp`), for compatibility with older versions of Atom.

Update core packages:
- [x] [symbols-view](https://github.com/atom/symbols-view) atom/symbols-view#65
- [x] [language-ruby](https://github.com/atom/language-ruby) atom/language-ruby#77
- [x] [language-gfm](https://github.com/atom/language-gfm) atom/language-gfm#64

Release and upgrade bundled packages:
- [x] language-c
- [x] language-objective-c
- [x] language-gfm
- [x] language-ruby
- [x] symbols-view

Send PRs to community packages:
- [x] [atom-ctags](https://github.com/yongkangchen/atom-ctags) yongkangchen/atom-ctags#39
- [x] [atom-lint](https://github.com/yujinakayama/atom-lint) yujinakayama/atom-lint#115
- [x] [atom-xikij](https://github.com/klorenz/atom-xikij) klorenz/atom-xikij#3
- [x] [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) yasuyuky/autocomplete-clang#23
- [x] [build-tools-cpp](https://github.com/deprint/build-tools-cpp) deprint/build-tools-cpp#9
- [x] [atom-clang-format](https://github.com/LiquidHelium/atom-clang-format) LiquidHelium/atom-clang-format#9
- [x] [coffee-navigator](https://github.com/suda/coffee-navigator) suda/coffee-navigator#16
- [x] [atom-file-types](https://github.com/execjosh/atom-file-types) execjosh/atom-file-types#7
- [x] [language-arduino](https://github.com/szechyjs/language-arduino) szechyjs/language-arduino#2
- [x] [language-crystal](https://github.com/somu/language-crystal) yegortimoschenko/language-crystal#2
- [x] [language-literate](https://github.com/kerrigan29a/language-literate) Kerrigan29a/language-literate#1
- [x] [language-swig](https://github.com/saki007ster/language-swig) saki007ster/language-swig#3
- [x] [language-x86](https://github.com/taylorlapeyre/language-x86) taylorlapeyre/language-x86#3
- [x] [linter-clang](https://github.com/AtomLinter/linter-clang) AtomLinter/linter-clang#18
- [x] [linter-cpplint](https://github.com/AtomLinter/linter-cpplint) AtomLinter/linter-cpplint#9
- [x] [symbols-tree-view](https://github.com/xndcn/symbols-tree-view) xndcn/symbols-tree-view#4

Refs #54.
